fourphonon_selfenergy – TDEP
fourphonon_selfenergy Subroutine
Source File
Description
The fourth order self-energy
subroutine fourphonon_selfenergy(qpoint, ompoint, qp, temperature, dr, uc, fc, fcf, delta, mw, verbosity)
Arguments
Type Intent Optional Attributes Name
type(lo_qpoint), intent(in) :: qpoint
qpoint for q
type(lo_phonon_dispersions_qpoint), intent(in) :: ompoint
harmonic properties for q
class(lo_qpoint_mesh), intent(in) :: qp
grid for q',q'',q'''
real(kind=flyt), intent(in) :: temperature
temperature
type(lo_phonon_dispersions), intent(in) :: dr
harmonic properties for q',q'',q''
type(lo_crystalstructure), intent(in) :: uc
cyrstal structure
type(lo_forceconstant_secondorder), intent(in) :: fc
second order force constant
type(lo_forceconstant_fourthorder), intent(in) :: fcf
third order force constant
real(kind=flyt), intent(out), dimension(:) :: delta
real four-phonon self-energy
type(lo_mpi_helper), intent(in) :: mw
mpi helper
integer, intent(in) :: verbosity
how much to talk
Calls
Called By
Call graph
fourphonon_selfenergy calls lo_truentimes, lo_planck, lo_progressbar, mpi_allreduce, walltime, lo_progressbar_init, lo_allocate
generate calls fourphonon_selfenergy