generate – TDEP
generate Subroutine
Source File
Description
Generate the self-energy at a single q-point
subroutine generate(se, qpoint, ompoint, uc, fc, fct, fcf, qp, dr, loto, opts)
Arguments
Type Intent Optional Attributes Name
class(lo_phonon_selfenergy), intent(out) :: se
self energy
class(lo_qpoint), intent(in) :: qpoint
qpoint of interest
type(lo_phonon_dispersions_qpoint), intent(in) :: ompoint
harmonic properties at this q-point
type(lo_crystalstructure), intent(in) :: uc
crystal structure
type(lo_forceconstant_secondorder), intent(in) :: fc
second order force constant
type(lo_forceconstant_thirdorder), intent(in) :: fct
third order force constant
type(lo_forceconstant_fourthorder), intent(in) :: fcf
fourth order force constant
type(lo_monkhorst_pack_mesh), intent(in) :: qp
q-point mesh
type(lo_phonon_dispersions), intent(in) :: dr
harmonic properties on this mesh
type(lo_loto), intent(in) :: loto
electrostatic corrections
type(lo_opts), intent(in) :: opts
all settings
Calls
Call graph
generate calls isotope_imaginary_selfenergy_gaussian, lo_linspace, threephonon_imaginary_selfenergy_gaussian, find_threephonon_scatteringrates, fourphonon_selfenergy, lo_trapezoid_integration, isotope_imaginary_selfenergy_tetrahedron, slightsmearing, find_isotope_scatteringrates, kramer_kronig_transform_to_get_real_part, flyt2char, threephonon_imaginary_selfenergy_tetrahedron, int2char
fourphonon_selfenergy calls lo_allocate, walltime, lo_get_small_group_of_qpoint, lo_get_dynamical_matrix, lo_get_omega_and_velocities, lo_deallocate, lo_planck
kramer_kronig_transform_to_get_real_part calls lo_trapezoid_integration