generate – TDEP
generate Subroutine
Source File
Description
set up all the coordination shells and stuff
private subroutine generate(mag, sl, uc, ss)
Arguments
Type Intent Optional Attributes Name
class(lo_magdisorder), intent(out) :: mag
to keep track of all the coordination shells
type(lo_symlist), intent(in) :: sl
a symmetry table, useful for a bunch of stuff
type(lo_crystalstructure), intent(in) :: uc
unit cell
type(lo_crystalstructure), intent(in) :: ss
supercell
Calls
Call graph
generate calls shelli, lo_allocate, lo_sqnorm, shellmag