get_intensity_as_dos – TDEP
get_intensity_as_dos Subroutine
Source File
Description
calculate things as a density of states
subroutine get_intensity_as_dos(qpd, drd, uc, fc, fct, fcf, qp, dr, loto, opts, mw, lsmpi)
Arguments
Type Intent Optional Attributes Name
type(lo_monkhorst_pack_mesh), intent(in) :: qpd
q-point mesh
type(lo_phonon_dispersions), intent(in) :: drd
harmonic properties on this mesh
type(lo_crystalstructure), intent(inout) :: uc
crystal structure
type(lo_forceconstant_secondorder), intent(in) :: fc
second order force constant
type(lo_forceconstant_thirdorder), intent(in) :: fct
third order force constant
type(lo_forceconstant_fourthorder), intent(in) :: fcf
fourth order force constant
type(lo_monkhorst_pack_mesh), intent(in) :: qp
q-point mesh
type(lo_phonon_dispersions), intent(in) :: dr
harmonic properties on this mesh
type(lo_loto), intent(in) :: loto
electrostatic corrections
type(lo_opts), intent(in) :: opts
all settings
type(lo_mpiinfo), intent(in) :: mw
mpi communicator
type(lo_lsmpi), intent(in) :: lsmpi
mpi helper
Calls
Call graph
get_intensity_as_dos calls lo_progressbar, mpi_allreduce, lo_gauss, getintensity, lo_trapezoid_integration, mpi_wtime, lo_allocate, lo_put_function_on_new_axis, omp_set_num_threads, lo_progressbar_init