get_thermally_broadened_intensity_along_path – TDEP
get_thermally_broadened_intensity_along_path Subroutine
Source File
Description
calculate the intensity along a path
subroutine get_thermally_broadened_intensity_along_path(bs, uc, fc, fct, fcf, qp, dr, loto, opts, mw, lsmpi)
Arguments
Type Intent Optional Attributes Name
type(lo_phonon_bandstructure), intent(inout) :: bs
the bandstructure
type(lo_crystalstructure), intent(inout) :: uc
crystal structure
type(lo_forceconstant_secondorder), intent(in) :: fc
second order force constant
type(lo_forceconstant_thirdorder), intent(in) :: fct
third order force constant
type(lo_forceconstant_fourthorder), intent(in) :: fcf
fourth order force constant
type(lo_monkhorst_pack_mesh), intent(in) :: qp
q-point mesh
type(lo_phonon_dispersions), intent(in) :: dr
harmonic properties on this mesh
type(lo_loto), intent(in) :: loto
electrostatic corrections
type(lo_opts), intent(in) :: opts
all settings
type(lo_mpiinfo), intent(in) :: mw
mpi communicator
type(lo_lsmpi), intent(in) :: lsmpi
mpi helper
Calls
Call graph
get_thermally_broadened_intensity_along_path calls dum, lo_linspace, lo_gauss, lo_seed_random_numbers, lo_progressbar, mpi_allreduce, lo_allocate, lo_deallocate, lo_progressbar_init, lo_sqnorm, lo_planck, harmonic_things_at_single_q, walltime