histfit – TDEP
histfit Subroutine
Source File
Description
write(,) 'bb',beta1,beta2
write(,) hessian
public subroutine histfit(sim)
Arguments
Type Intent Optional Attributes Name
type(lo_mdsim), intent(inout) :: sim
force-displacement data
Calls
Call graph
histfit calls lo_trapezoid_integration, lo_linspace, y, par0, open_file, lo_identitymatrix, lo_allocate