iso_tetrahedron_fft_oneqp – TDEP
iso_tetrahedron_fft_oneqp Subroutine
Source File
Description
Tetrahedron integration weights for isotope scattering, from one q-point
subroutine iso_tetrahedron_fft_oneqp(qp, dr, scq, gi1, scsigma, blochlcorrections)
Arguments
Type Intent Optional Attributes Name
class(lo_qpoint_mesh), intent(in) :: qp
qpoint mesh
type(lo_phonon_dispersions), intent(in) :: dr
phonon dispersoins
type(lo_iso2), intent(inout) :: scq
current q-point
integer, intent(in) :: gi1
current grid-index
real(kind=flyt), intent(in) :: scsigma
baseline smearing parameter
logical, intent(in) :: blochlcorrections
blochl corrections?
Calls
Call graph
iso_tetrahedron_fft_oneqp calls lo_sqnorm, lo_stop_gracefully, lo_allocate, lo_deallocate, lo_integration_weights_for_one_tetrahedron, lo_stddev