optimize – TDEP
optimize Subroutine
Source File
Description
generate optimized configuration
private subroutine optimize(mag, ss, nconf, nbin)
Arguments
Type Intent Optional Attributes Name
class(lo_magdisorder), intent(inout) :: mag
shells and stuff
type(lo_crystalstructure), intent(in) :: ss
crystal structure
integer, intent(in) :: nconf
how many configurations do I want in each bin?
integer, intent(in) :: nbin
how many bins?
Calls
Call graph
optimize calls zerosum, convcheck, lo_rotation_matrix_from_vector_a_to_b, lo_chop, conf1, lo_mean, lo_random_int, noncollhist, lo_allocate, ncconf1, tochar, collhist, random_unit_vector, ncconf0
random_unit_vector calls lo_random_gaussian_number