spectralfunction_along_path – TDEP
spectralfunction_along_path Subroutine
Source File
Description
Calculate the spectral function along a path in the BZ
subroutine spectralfunction_along_path(bs, uc, fc, fct, fcf, qp, dr, opts, mw)
Arguments
Type Intent Optional Attributes Name
type(lo_phonon_bandstructure), intent(inout) :: bs
the bandstructure
type(lo_crystalstructure), intent(inout) :: uc
crystal structure
type(lo_forceconstant_secondorder), intent(inout) :: fc
second order force constant
type(lo_forceconstant_thirdorder), intent(in) :: fct
third order force constant
type(lo_forceconstant_fourthorder), intent(in) :: fcf
fourth order force constant
class(lo_qpoint_mesh), intent(in) :: qp
q-point mesh
type(lo_phonon_dispersions), intent(in) :: dr
harmonic properties on this mesh
type(lo_opts), intent(in) :: opts
all settings
type(lo_mpi_helper), intent(inout) :: mw
mpi communicator
Calls
Call graph
spectralfunction_along_path calls dumim, lo_trapezoid_integration, lsinty, kernel, getintensity, lo_gauss, dum, dumre, y, lo_looptimer, lo_progressbar, x, lsintx, lo_lorentz, walltime, lo_progressbar_init, tochar, lo_linear_interpolation, z, lo_allocate