subtract_longrange_interactions – TDEP
subtract_longrange_interactions Subroutine
Source File
Description
remove longrange interactions
public subroutine subtract_longrange_interactions(sim, map, uc, ss)
Arguments
Type Intent Optional Attributes Name
type(lo_mdsim), intent(inout) :: sim
force-displacement data
type(lo_forcemap), intent(in) :: map
forcemap
type(lo_crystalstructure), intent(inout) :: uc
unitcell
type(lo_crystalstructure), intent(inout) :: ss
supercell
Calls
Call graph
subtract_longrange_interactions calls lo_truentimes, lo_frobnorm, lo_progressbar, lo_allocate, lo_progressbar_init, walltime