test_forceconstant_constraints – TDEP
test_forceconstant_constraints Subroutine
Source File
public subroutine test_forceconstant_constraints(map, fc1, fc2, fc3, fc4, uc)
Arguments
Type Intent Optional Attributes Name
type(lo_forcemap), intent(in) :: map
all the forceconstant metadata
type(lo_forceconstant_firstorder), intent(in) :: fc1
firstorder forceconstant
type(lo_forceconstant_secondorder), intent(in) :: fc2
secondorder forceconstant
type(lo_forceconstant_thirdorder), intent(in) :: fc3
thirdorder forceconstant
type(lo_forceconstant_fourthorder), intent(in) :: fc4
fourthorder forceconstant
type(lo_crystalstructure), intent(in) :: uc
crystal structure
Calls
Call graph
test_forceconstant_constraints calls di, lo_sqnorm, r, lo_deallocate, m0, tochar, m1, lo_allocate