threephonon_gaussian_fft_oneqp – TDEP
threephonon_gaussian_fft_oneqp Subroutine
Source File
Description
count three-phonons scattering events with gaussian smearing
subroutine threephonon_gaussian_fft_oneqp(qp, dr, scq, gi1, scsigma, thres, adaptiveparameter, progressbar)
Arguments
Type Intent Optional Attributes Name
class(lo_qpoint_mesh), intent(in) :: qp
type(lo_phonon_dispersions), intent(in) :: dr
type(lo_3phqp2), intent(inout) :: scq
integer, intent(in) :: gi1
real(kind=flyt), intent(in) :: scsigma
real(kind=flyt), intent(in) :: thres
real(kind=flyt), intent(in), optional :: adaptiveparameter
logical, intent(in), optional :: progressbar
Calls
Call graph
threephonon_gaussian_fft_oneqp calls fft_third_grid_index, lo_gauss, lo_progressbar, lo_allocate, lo_deallocate, lo_progressbar_init