threephonon_tetrahedron_fft_oneqp – TDEP
threephonon_tetrahedron_fft_oneqp Subroutine
Source File
Description
Tetrahedron integration weights for threephonon scattering, from one q-point
subroutine threephonon_tetrahedron_fft_oneqp(qp, dr, scq, gi1, scsigma, blochlcorrections)
Arguments
Type Intent Optional Attributes Name
class(lo_qpoint_mesh), intent(in) :: qp
qpoint mesh
type(lo_phonon_dispersions), intent(in) :: dr
phonon dispersions
type(lo_3phqp2), intent(inout) :: scq
q-point in question
integer, intent(in) :: gi1
grid-index in question
real(kind=flyt), intent(in) :: scsigma
baseline smearing
logical, intent(in) :: blochlcorrections
blochl corrections?
Calls
Call graph
threephonon_tetrahedron_fft_oneqp calls fft_third_grid_index, lo_lv_tetrahedron_weights, lo_stop_gracefully, lo_allocate, lo_deallocate, lo_sqnorm, lo_integration_weights_for_one_tetrahedron